import '../../domain/models/charity_item.dart';
import '../../domain/models/financial_report.dart';
import '../../domain/models/user_profile.dart';

class DummyData {
  static final UserProfile currentUser = UserProfile(
    id: 'user1',
    name: 'أحمد',
    totalTasbih: 128,
    adsViewed: 450,
    dailyStreak: 7,
    level: 'ذهبي',
  );

  static final List<CharityItem> charityItems = [
    CharityItem(
      id: 'c1',
      title: 'إطعام وجبة',
      description: 'تقديم وجبة ساخنة لأسرة محتاجة',
      price: 10.0,
      category: 'Direct Impact',
      imageUrl: '',
      impactMetric: 'وجبة',
      impactCount: 1,
    ),
    CharityItem(
      id: 'c2',
      title: 'علاج ودواء',
      description: 'توفير العلاج والدواء لمريض محتاج',
      price: 50.0,
      category: 'Direct Impact',
      imageUrl: '',
      impactMetric: 'مريض',
      impactCount: 1,
    ),
    CharityItem(
      id: 'c3',
      title: 'سقي ماء',
      description: 'توفير مياه شرب نظيفة',
      price: 20.0,
      category: 'Direct Impact',
      imageUrl: '',
      impactMetric: 'شخص',
      impactCount: 10,
    ),
    CharityItem(
      id: 'c4',
      title: 'مصحف',
      description: 'طباعة وتوزيع مصحف',
      price: 30.0,
      category: 'Direct Impact',
      imageUrl: '',
      impactMetric: 'مصحف',
      impactCount: 1,
    ),
    CharityItem(
      id: 'c5',
      title: 'كسوة يتيم',
      description: 'توفير كسوة كاملة ليتيم',
      price: 40.0,
      category: 'Direct Impact',
      imageUrl: '',
      impactMetric: 'يتيم',
      impactCount: 1,
    ),
    CharityItem(
      id: 'c6',
      title: 'بناء بئر',
      description: 'حفر بئر ماء في منطقة محتاجة',
      price: 0,
      category: 'Sustainable Impact',
      imageUrl: '',
      impactMetric: 'قرية',
      impactCount: 1,
      isProject: true,
      targetAmount: 5000,
      raisedAmount: 3200,
      contributorsCount: 64,
    ),
    CharityItem(
      id: 'c7',
      title: 'إيواء أسرة',
      description: 'توفير سكن لأسرة بلا مأوى',
      price: 0,
      category: 'Sustainable Impact',
      imageUrl: '',
      impactMetric: 'أسرة',
      impactCount: 1,
      isProject: true,
      targetAmount: 15000,
      raisedAmount: 8700,
      contributorsCount: 174,
    ),
    CharityItem(
      id: 'c8',
      title: 'بناء غرفة',
      description: 'إضافة غرفة لأسرة محتاجة',
      price: 0,
      category: 'Sustainable Impact',
      imageUrl: '',
      impactMetric: 'غرفة',
      impactCount: 1,
      isProject: true,
      targetAmount: 3000,
      raisedAmount: 2100,
      contributorsCount: 42,
    ),
    CharityItem(
      id: 'c9',
      title: 'أبحاث علمية',
      description: 'دعم البحث العلمي في المجالات الطبية',
      price: 0,
      category: 'Ummah Development',
      imageUrl: '',
      impactMetric: 'بحث',
      impactCount: 1,
      isProject: true,
      targetAmount: 25000,
      raisedAmount: 9800,
      contributorsCount: 196,
    ),
    CharityItem(
      id: 'c10',
      title: 'دعم تصنيع الأدوية',
      description: 'المساهمة في تصنيع أدوية بأسعار مخفضة',
      price: 0,
      category: 'Ummah Development',
      imageUrl: '',
      impactMetric: 'دواء',
      impactCount: 100,
      isProject: true,
      targetAmount: 50000,
      raisedAmount: 12400,
      contributorsCount: 248,
    ),
    CharityItem(
      id: 'c11',
      title: 'مشاريع تعليمية',
      description: 'بناء مدارس ودعم التعليم في المناطق المحتاجة',
      price: 0,
      category: 'Ummah Development',
      imageUrl: '',
      impactMetric: 'طالب',
      impactCount: 50,
      isProject: true,
      targetAmount: 20000,
      raisedAmount: 6500,
      contributorsCount: 130,
    ),
    CharityItem(
      id: 'c12',
      title: 'الابتكار التقني',
      description: 'دعم المشاريع التقنية الناشئة في العالم الإسلامي',
      price: 0,
      category: 'Ummah Development',
      imageUrl: '',
      impactMetric: 'مشروع',
      impactCount: 1,
      isProject: true,
      targetAmount: 30000,
      raisedAmount: 5000,
      contributorsCount: 100,
    ),
  ];

  static final FinancialReport financialReport = FinancialReport(
    id: 'r1',
    title: 'التقرير المالي الشهري',
    period: DateTime(2026, 5, 1),
    adRevenue: 12500.00,
    donationsReceived: 87300.00,
    operationalCosts: 3200.00,
    totalCharitySpent: 84500.00,
    completedProjects: 7,
  );
}
